[package]
name = "tonutils-tlb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TL-B data models and serialization for TON."
readme = "../../README.md"
documentation = "https://docs.rs/tonutils-tlb"
keywords = ["ton", "tlb", "serialization", "blockchain", "tvm"]
categories = ["encoding", "cryptography::cryptocurrencies"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
num-bigint.workspace = true
thiserror.workspace = true
tonutils-macros = { path = "../tonutils-macros", version = "2.0.0" }
tonutils-tvm = { path = "../tonutils-tvm", version = "2.0.0" }

[dev-dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
