[package]
name = "tonutils-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Low-level TON smart-contract provider and message helpers."
readme = "../../README.md"
documentation = "https://docs.rs/tonutils-contracts"
keywords = ["ton", "blockchain", "smart-contracts", "liteclient", "tvm"]
categories = ["api-bindings", "cryptography::cryptocurrencies"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
num-bigint.workspace = true
thiserror.workspace = true
tonutils-crc = { path = "../tonutils-crc", version = "2.0.0" }
tonutils-tl = { path = "../tonutils-tl", version = "2.0.0" }
tonutils-tlb = { path = "../tonutils-tlb", version = "2.0.0" }
tonutils-tvm = { path = "../tonutils-tvm", version = "2.0.0" }
