[package]
name = "tonutils-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-trait = "0.1.89"
num-bigint = "0.4.6"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.143"
tokio = "1.47.1"
tonlib-core = "0.26.1"
