[workspace]
resolver = "3"
members = [
    "crates/tonutils-adnl",
    "crates/tonutils-cli",
    "crates/tonutils-contracts",
    "crates/tonutils-crc",
    "crates/tonutils-jetton",
    "crates/tonutils-liteclient",
    "crates/tonutils-macros",
    "crates/tonutils-metadata",
    "crates/tonutils-network-config",
    "crates/tonutils-nft",
    "crates/tonutils-tl",
    "crates/tonutils-tlb",
    "crates/tonutils-tvm",
    "crates/tonutils-wallet",
]
default-members = [
    "crates/tonutils-cli",
    "crates/tonutils-contracts",
    "crates/tonutils-jetton",
    "crates/tonutils-liteclient",
    "crates/tonutils-nft",
    "crates/tonutils-wallet",
]

[workspace.package]
version = "2.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/lapismyt/tonutils-rs"
rust-version = "1.85"

[workspace.dependencies]
aes = "0.8"
anyhow = "1.0.99"
async-trait = "0.1.89"
base64 = "0.23"
bip39 = { version = "2.1", features = ["rand"] }
byteorder = "1.5"
clap = { version = "4.5", features = ["derive"] }
crc = "3.3.0"
crc32fast = "1.4"
criterion = "0.8"
ctr = "0.9"
curve25519-dalek = "4.1"
derivative = "2.2"
ed25519-dalek = "2.1"
futures = "0.3"
hex = "0.4"
hmac = "0.12"
log = "0.4"
num-bigint = "0.5.1"
pbkdf2 = "0.12"
pin-project = "1.1.10"
pretty_env_logger = "0.5.0"
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.150"
serde_with = { version = "3.21", features = ["base64"] }
sha2 = "0.10"
syn = { version = "2.0", features = ["full"] }
thiserror = "2.0.17"
tl-proto = { version = "0.5.3", features = ["derive"] }
tl-scheme = "0.3.0"
tokio = { version = "1.47.1", features = ["full", "time"] }
tokio-tower = "0.6.0"
tokio-util = { version = "0.7.16", features = ["codec"] }
tower = { version = "0.5", features = ["make", "util"] }
ureq = { version = "3.1.2", features = ["socks-proxy"] }
