[package]
name = "tonutils-tl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TL schema types and LiteAPI serialization for TON."

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
derivative.workspace = true
hex.workspace = true
rand.workspace = true
thiserror.workspace = true
tl-proto.workspace = true

[dev-dependencies]
tl-scheme.workspace = true
