[package]
name = "tonutils-mempool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Low-latency Rust stream for TON pending external messages."
readme = "../../README.md"
documentation = "https://docs.rs/tonutils-mempool"
keywords = ["ton", "mempool", "overlay", "blockchain"]
categories = ["network-programming", "cryptography::cryptocurrencies"]

[lints]
workspace = true

[dependencies]
tonutils-adnl = { path = "../tonutils-adnl", version = "2.0.0", features = ["udp"] }
futures.workspace = true
hex.workspace = true
raptorq.workspace = true
log.workspace = true
reqwest.workspace = true
rand.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonutils-overlay = { path = "../tonutils-overlay", version = "2.0.0" }
tonutils-network-config = { path = "../tonutils-network-config", version = "2.0.0" }
tonutils-tlb = { path = "../tonutils-tlb", version = "2.0.0" }
tonutils-tl = { path = "../tonutils-tl", version = "2.0.0" }
tl-proto.workspace = true
tonutils-tvm = { path = "../tonutils-tvm", version = "2.0.0" }
