use tonutils_tlb::schema;

fn main() -> anyhow::Result<()> {
    let user_schema = r#"
        demo_state$10 seqno:uint32 owner:bits256 = DemoState;
        demo_empty$0 = DemoMaybe;
    "#;
    let user_constructors = schema::parse_schema(user_schema)?;
    let user_summary = schema::generate_summary(&user_constructors);

    let block_constructors = schema::parse_schema(schema::BLOCK_TLB)?;
    let block_generated = schema::generate_block_summary()?;

    println!("user_constructors={}", user_constructors.len());
    println!("user_summary={user_summary}");
    println!("block_constructors={}", block_constructors.len());
    println!(
        "block_summary_generated={}",
        block_generated.contains("@generated by tonutils TL-B schema generator")
    );
    Ok(())
}
