[package]
name = "tonutils-adnl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Native Rust ADNL primitives and TCP transport for TON."
readme = "../../README.md"
documentation = "https://docs.rs/tonutils-adnl"
keywords = ["ton", "adnl", "networking", "tcp", "blockchain"]
categories = ["network-programming", "cryptography::cryptocurrencies"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[features]
default = ["tcp"]
tcp = ["dep:futures", "dep:pin-project", "dep:tokio", "dep:tokio-util"]
udp = ["dep:futures", "dep:pin-project", "dep:tokio", "dep:tokio-util"]

[dependencies]
aes.workspace = true
ctr.workspace = true
curve25519-dalek.workspace = true
futures = { workspace = true, optional = true }
hex.workspace = true
log.workspace = true
pin-project = { workspace = true, optional = true }
rand.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tl-proto.workspace = true
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
tonutils-tl = { path = "../tonutils-tl", version = "2.0.0" }

[dev-dependencies]
serde_json.workspace = true
