[package]
name = "tonutils-network-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TON global network configuration parsing."

[lints]
workspace = true

[dependencies]
base64.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
