[package]
name = "tonutils-network-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TON global network configuration parsing."
readme = "../../README.md"
documentation = "https://docs.rs/tonutils-network-config"
keywords = ["ton", "network", "liteserver", "configuration", "blockchain"]
categories = ["config", "network-programming"]

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
