[package]
name = "tonutils-jetton"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TON jetton payloads, metadata, and get-method decoders."

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[features]
default = []
provider = ["dep:tonutils-contracts"]

[dependencies]
num-bigint.workspace = true
thiserror.workspace = true
tonutils-crc = { path = "../tonutils-crc", version = "2.0.0" }
tonutils-contracts = { path = "../tonutils-contracts", version = "2.0.0", optional = true }
tonutils-metadata = { path = "../tonutils-metadata", version = "2.0.0" }
tonutils-tlb = { path = "../tonutils-tlb", version = "2.0.0" }
tonutils-tvm = { path = "../tonutils-tvm", version = "2.0.0" }
